apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy6651
  labels:
    app: autodeploy6651
  namespace: namespace-workflow-1710346957527
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy6651
  template:
    metadata:
      labels:
        app: autodeploy6651
    spec:
      containers:
        - name: autodeploy6651
          image: acrworkflow1710346957527.azurecr.io/image-workflow-1710346957527:latest
          ports:
            - containerPort: 5000